// Generated by `wit-bindgen` 0.36.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod s4 {
        pub mod files {
            #[allow(dead_code, clippy::all)]
            pub mod gfx {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                wit_bindgen_rt::bitflags::bitflags! {
                    #[derive(PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Clone, Copy)]
                    pub struct Unknown : u8 { const TODO = 1 << 0; }
                }
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum ImageKind {
                    Unknown,
                }
                impl ::core::fmt::Debug for ImageKind {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            ImageKind::Unknown => {
                                f.debug_tuple("ImageKind::Unknown").finish()
                            }
                        }
                    }
                }
                impl ImageKind {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> ImageKind {
                        if !cfg!(debug_assertions) {
                            return ::core::mem::transmute(val);
                        }
                        match val {
                            0 => ImageKind::Unknown,
                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }
                #[doc(hidden)]
                macro_rules! __export_s4_files_gfx_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = {};
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_s4_files_gfx_0_1_0_cabi;
            }
        }
    }
}
/// Generates `#[no_mangle]` functions to export the specified type as the
/// root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_files_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::s4::files::gfx::__export_s4_files_gfx_0_1_0_cabi!($ty with_types_in
        $($path_to_types_root)*:: exports::s4::files::gfx);
    };
}
#[doc(inline)]
pub(crate) use __export_files_impl as export;
#[cfg(target_arch = "wasm32")]
#[link_section = "component-type:wit-bindgen:0.36.0:s4:files@0.1.0:files:encoded world"]
#[doc(hidden)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 416] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xa4\x02\x01A\x02\x01\
A\x02\x01B\x12\x01n\x01\x04todo\x04\0\x07unknown\x03\0\0\x01m\x01\x07unknown\x04\
\0\x0aimage-kind\x03\0\x02\x01o\x02{{\x01p}\x01r\x06\x0adimensions\x04\x0bpaddin\
g-top{\x0cpadding-left{\x04kind\x03\x04meta\x01\x04data\x05\x04\0\x05image\x03\0\
\x06\x01p{\x04\0\x07palette\x03\0\x08\x01py\x04\0\x0dimage-indices\x03\0\x0a\x01\
py\x04\0\x11direction-indices\x03\0\x0c\x01py\x04\0\x0fpalette-indices\x03\0\x0e\
\x01py\x04\0\x0bjob-indices\x03\0\x10\x04\0\x12s4:files/gfx@0.1.0\x05\0\x04\0\x14\
s4:files/files@0.1.0\x04\0\x0b\x0b\x01\0\x05files\x03\0\0\0G\x09producers\x01\x0c\
processed-by\x02\x0dwit-component\x070.220.0\x10wit-bindgen-rust\x060.36.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
